### ISSUE TITLE
Progressive web app score and performance score

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#502]
Here are two little problems I have seen in the pwa-directory web site
1°)
Some apps such as Hello word PWA or workbox on the first page of https://pwa-directory.appspot.com/pwas/score
do not have a score of 100 but are displayed with a score of 100
https://pwa-directory.appspot.com/pwas/5146802429362176
https://pwa-directory.appspot.com/pwas/5150973500588032

2°) my app which is 
https://web-performance-dot-pwa-directory.appspot.com/lighthouse-viewer/?pwadir=5159185788436480
is installable and when I audit it with lighthouse from my place ( Paris, France ), it has a performance score equal to 96, 
all others scores are 100, but your lighthouse report displays a performance score equal to 53.

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

Thank you for contacting us.

1) it is a bug that we do not update the Lighthouse score for stalled/broken PWAs, we should demote those PWAs after X time when they are broken.

2) Performance is a bit tricky because we run Lighthouse scores in a VM environment, I will debug it further and try to make sure it rates closer to the one you get in a PC, when I run it at the moment it gives a 73, so it is normal for some of the checks to vary depending on the circumstances.

Thanks,
Julian

**Comment by hugues-koolsol** [comment]
Hi Julian, thank you for your quick reply,

I run on my windows 10 pc a little php program with a command line and I scan the first 32 urls of the pwas on the pwa-directory score page,
It outputs a csv (see attached file) and if you want this php program, I will send it to you.

This gulliver/lighthouse/pwa-directory is a fabulous idea :-)

Thanks
Hugues

[out.csv.txt](https://github.com/GoogleChromeLabs/gulliver/files/2164112/out.csv.txt)
